---
dist: trusty
language: python
sudo: required
cache:
  pip: true

env:
  global:
    - fast_finish: true

matrix:
  include:
#    - env: TAG=2.4  # 2.4.x bugs and security
#    - env: TAG=2.5  # 2.4.x bugs and security
#    - env: TAG=2.6  # Development
    - env: TAG=test  # Development

services:
  - docker

addons:
  apt:
    sources:
      - docker-trusty
    packages:
      - docker-ce

before_install:
  - sudo apt-get -qq update && sudo apt-get remove -y lxd

install:
  - sudo apt-get -y install snapd python3.5
  - sudo snap install lxd
  - sudo sudo bash -c 'echo PATH=/snap/bin:$PATH >> /etc/environment'
  - while [ ! -S /var/snap/lxd/common/lxd/unix.socket ]; do echo "Waiting for LXD socket...";sleep 0.2;done;
  - curl https://raw.githubusercontent.com/LANsible/ansible-dev-container/lxd/setup-lxd.sh | sudo bash -s -- password

script:
  - docker run --net=host -it -v $(pwd):/data/$(basename ~+) -w /data/$(basename ~+) lansible/ansible-dev-container:$TAG molecule --debug converge

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email:
    on_failure: change
    on_success: never
