language: python
sudo: required
dist: trusty
cache:
  directories: [ '$HOME/lxc' ]
  pip: true
env:
  - LXC_DISTRO=debian LXC_RELEASE=jessie
  - LXC_DISTRO=debian LXC_RELEASE=wheezy
  - LXC_DISTRO=ubuntu LXC_RELEASE=xenial
  - LXC_DISTRO=ubuntu LXC_RELEASE=trusty
  - LXC_DISTRO=centos LXC_RELEASE=7
  - LXC_DISTRO=centos LXC_RELEASE=6
#  - ANSIBLE_VERSION='ansible>=1.9.0,<2.0.0' #EOL 2016-04-15
#  - ANSIBLE_VERSION='ansible>=2.0.0,<2.1.0' #EOL 2016-04-19
#  - ANSIBLE_VERSION='ansible>=2.1.0,<2.2.0' #EOL 2017-06-01
  - ANSIBLE_VERSION='ansible>=2.2.0,<2.3.0' #EOL 2017-05-09
  - ANSIBLE_VERSION='ansible>=2.3.0,<2.4.0' #EOL 2017-06-01
  - ANSIBLE_VERSION='git+https://github.com/ansible/ansible.git@devel' #DEVEL

before_cache:
  - if [ ! "$ANSIBLE_VERSION" ]; then sudo mkdir $HOME/lxc && sudo tar cf $HOME/lxc/cache.tar /var/cache/lxc/ && sudo chown $USER. $HOME/lxc/cache.tar; fi

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y expect-dev nmap

install:
  - if [ ! "$ANSIBLE_VERSION" ]; then sudo tar xf $HOME/lxc/cache.tar -C / || true; fi
  - if [ "$ANSIBLE_VERSION" ]; then pip install $ANSIBLE_VERSION; else pip install ansible; fi
  - ansible --version
  - printf '[defaults]\nroles_path=../\ncallback_whitelist=profile_tasks' >ansible.cfg

before_script:
  - if [ ! "$ANSIBLE_VERSION" ]; then ansible-galaxy install lae.travis-lxc; fi
  - if [ ! "$ANSIBLE_VERSION" ]; then ansible-playbook -vvv tests/install.yml; fi

script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - if [ ! "$ANSIBLE_VERSION" ]; then ansible-playbook -vvv tests/test.yml -i tests/inventory; fi
#  - unbuffer ansible-playbook -vvv tests/test.yml -i tests/inventory >/tmp/idempotency.log 2>&1
#  - 'grep -A1 "PLAY RECAP" /tmp/idempotency.log | grep -qP "changed=0.*failed=0" && (echo "Idempotence: PASS"; exit 0) || (echo "Idempotence: FAIL"; cat /tmp/idempotency.log; exit 1)'
  - if [ ! "$ANSIBLE_VERSION" ]; then ssh root@test01.lxc /bin/bash -c "PAGER=cat journalctl -xn || cat /var/log/messages || cat /var/log/syslog"; fi

#deploy:
#  - provider: script
#    script: deploy/deploy.sh plex
#    on:
#      branch: master