---
dist: trusty
language: python
sudo: required
cache:
  pip: true

env:
  global:
    - fast_finish: true

matrix:
  include:
    - env: TAG=latest
#    - env: TAG=2.3  # 2.3.x bugs and security
#    - env: TAG=2.4  # 2.4.x bugs and security
#    - env: TAG=2.5  # 2.4.x bugs and security
#    - env: TAG:2.6  # Development

services:
  - docker

addons:
  apt:
    sources:
      - docker-trusty
    packages:
      - docker-ce

script:
  - sudo service docker stop
  - sudo docker -H tcp://127.0.0.1:2375 -d
  - docker run --net=host -t -v $(pwd):/data/$(basename ~+) -w /data/$(basename ~+) lansible/ansible-dev-container:$TAG converge

notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  email:
    on_failure: change
    on_success: never
