language: python
sudo: required
dist: trusty
cache:
  directories: [ '$HOME/lxc' ]
  pip: true
env:
  - LXC_DISTRO=debian LXC_RELEASE=jessie
  - LXC_DISTRO=debian LXC_RELEASE=wheezy
  - LXC_DISTRO=ubuntu LXC_RELEASE=xenial
  - LXC_DISTRO=ubuntu LXC_RELEASE=trusty
  - LXC_DISTRO=centos LXC_RELEASE=7
  - LXC_DISTRO=centos LXC_RELEASE=6
before_cache:
  - sudo mkdir $HOME/lxc && sudo tar cf $HOME/lxc/cache.tar /var/cache/lxc/ && sudo chown $USER. $HOME/lxc/cache.tar
install:
  - sudo tar xf $HOME/lxc/cache.tar -C / || true
  - sudo apt-get install -y expect-dev
  - pip install ansible
  - ansible --version
before_script:
  - ansible-galaxy install lae.travis-lxc
  - ansible-playbook -vvv tests/install.yml
script:
  - ansible-playbook tests/test.yml -i tests/inventory --syntax-check
  - ansible-playbook tests/test.yml -i tests/inventory  - ANSIBLE_STDOUT_CALLBACK=debug ansible-playbook -i test01.lxc, -vvv .travis-playbook.yml
  - unbuffer ansible-playbook -vvv tests/test.yml -i tests/inventory >/tmp/idempotency.log 2>&1
  - 'grep -A1 "PLAY RECAP" /tmp/idempotency.log | grep -qP "changed=0.*failed=0" && (echo "Idempotence: PASS"; exit 0) || (echo "Idempotence: FAIL"; cat /tmp/idempotency.log; exit 1)'
  - ssh root@test01.lxc /bin/bash -c "PAGER=cat journalctl -xn || cat /var/log/messages || cat /var/log/syslog"