---
# tasks file for plex
- include: plex.yml

- include: plexpy.yml
  when: plexpy_install

- include: plexupdate.yml
  when: plexupdate_install

- include: postfix.yml
  when: plexupdate_notify

- include: configure-firewalld.yml
  when: ansible_os_family == "RedHat"