---
- name: Install git
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - wget
    - git

- name: Clone plexupdate repository
  git:
    repo: https://github.com/mrworf/plexupdate.git
    dest: "{{ plexupdate_install_location }}"
    version: "{{ plexupdate_version }}"

- name: Create desired config
  template:
    src: plexupdate/plexupdate.conf.j2
    dest: "{{ plexupdate_config_location }}"

- name: Create cron config
  template:
    src: plexupdate/plexupdate.cron.conf.j2
    dest: "/etc/plexupdate.cron.conf"
  when: plexupdate_autoinstall or plexupdate_autoupdate

- name: Create cron job
  file:
    src: "{{ plexupdate_install_location }}/extras/cronwrapper"
    dest: "{{ plexupdate_cronwrapper }}"
    state: link
  when: plexupdate_autoinstall or plexupdate_autoupdate

- name: Install latest plex with plexupdate
  shell: "printfs 'Y\n' | {{ plexupdate_install_location }}/plexupdate.sh --config {{ plexupdate_config_location }}"
  changed_when: "'already installed' not in plexupdate_output.stdout"
  register: plexupdate_output
  notify: restart plex
