---
- name: Install git & ca-certificates
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - git
    - ca-certificates

- name: Install which untill PR is accepted
  yum:
    name: which
    state: present
  when: ansible_os_family == "RedHat"

- name: Create user
  group:
    name: "{{ tautulli_group }}"
    state: present

- name: Create user
  user:
    name: "{{ tautulli_user }}"
    group: "{{ tautulli_group }}"
    createhome: no

- name: Clone Tautulli repo
  git:
    repo: https://github.com/Tautulli/Tautulli.git
    dest: "{{ tautulli_install_location }}"

- name: Set permissions
  file:
    path: "{{ tautulli_install_location }}"
    owner: "{{ tautulli_user }}"
    group: "{{ tautulli_group }}"
    recurse: yes
  changed_when: false

- block:
    - name: Move init script for using systemd
      template:
        src: tautulli/init-systemd.j2
        dest: /lib/systemd/system/tautulli.service
        owner: root
        group: root
        mode: 0775

    - name: Autostart Tautulli and restart service
      systemd:
        name: tautulli
        enabled: yes
        daemon_reload: yes
      notify: restart tautulli

  when: (ansible_distribution == 'CentOS' and ansible_distribution_major_version == "7") or
        (ansible_distribution == 'Ubuntu' and ansible_distribution_version|int >= 15.04) or
        (ansible_distribution == 'Debian' and ansible_distribution_major_version|int >= 8)

- block:
    - name: Setup Software Collections
      yum:
        name: centos-release-scl
        state: present

    - name: Setup Python 2.7
      yum:
        name: python27
        state: latest

    - name: Move init script Centos 6
      template:
        src: tautulli/init-centos-fedora.j2
        dest: /etc/init.d/tautulli
        owner: root
        group: root
        mode: 0775
      notify: restart tautulli

    - name: Autostart Tautulli and restart service
      service:
        name: tautulli
        enabled: yes
      notify: restart tautulli

  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version == '6'

- block:
    - name: Move init script for older ubuntu versions
      file:
        src: "{{ tautulli_install_location }}/init-scripts/init.ubuntu"
        dest: /etc/init.d/tautulli
        owner: root
        group: root
        mode: 0775
        state: link

    - name: Set defaults in file
      template:
        src: tautulli/ubuntu-tautulli-defaults.j2
        dest: /etc/default/tautulli

    - name: Autostart Tautulli and restart service
      service:
        name: tautulli
        enabled: yes
      notify: restart tautulli

  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version|int <= 15.10