---
- name: Converge
  hosts: all
  roles:
    - role: ansible-role-plex

  post_tasks:
    - name: Wait for Plex to succesfully restart
      wait_for:
        port: 32400

    - name: Test Plex webinterface
      uri:
        url: "http://{{ inventory_hostname }}:32400/web"

    - name: Wait for Tautulli to succesfully restart
      wait_for:
        port: 8181

    - name: Test Tautulli webinterface
      uri:
        url: "http://{{ inventory_hostname }}:8181/home"
      when: tautulli_install

    - name: Grab system Logs
      shell: "journalctl -xn || cat /var/log/messages || cat /var/log/syslog"
      environment:
        - PAGER: cat
      changed_when: false
      ignore_errors: true
